### ISSUE TITLE
New training code is eating memory

### ISSUE THREAD

**Issue by eighttails** [mittagessen/kraken#200]
I'm trying to train Japanese OCR model using 2637 images with PAGE xml files.
`ketos train -d cuda:0 -f page -F 1 -q early --augment -o jpn *.xml`

With 3.0b5 ketos consumes about 2.1GB memory and it is reasonable.
With master(patch https://github.com/mittagessen/kraken/pull/199 is needed to run) ketos is eating more than 30GB memory and hangs.

It seems all images are stored in memory. Is there any option not to do that?

**Comment by mittagessen** [comment]
I've merged the batching code in the meanwhile. It shouldn't gobble up 30Gb of memory especially without separate loader threads but delayed garbage collection in combination with large images might be culprit. Alternatively, there is a memory preload mode enabled by default that should disable itself when training with more than 2500 lines. `--no-preload` will disable it explicitly. In addition you can try reducing the batch size to 1 with the `-B 1` option.

If either of those options resolve your problem it should be quite easy to fix.

**Comment by eighttails** [comment]
I pulled latest master and added both `--no-preload` and `-B 1` options but it didn't help...
Here is Console output and ketos hangs at `Initializing model ✓`

```
Building training set  [####################################]  118863/118863
Building validation set  [####################################]  13499/13499          [67.1518] alphabet mismatch: chars in training set only: {'┣', '矮', '杞', '競', '干', '喪', '馳', 'Θ', '𝐹', '砂', '庁', '怠', '迣', '授', '屯', '逃', '冒', '販', '晚', '唅', '罐', '洎', '招', '箱', 'ĵ', 'ɸ', '餌', '𠅘', ' 慈', '裪', '棒', '齟', '鎖', '〇', '\uf06c', '†', 'ゃ', '舞', '兆', '蠛', '┫', '⓻', '創', '佘', 'Ḿ', ' 夤', '凡', '∧', '革', '└', '歷', '焫', '¤', '隆', '栘', '捕', '勢', '›', '享', '諸', '嘆', '黄', '岳', '忙', '矦', '邈', '¶', '旦', '締', '芸', '永', '羡', '博', '螘', 'ヸ', 'Ǐ', '〕', '┓', '寨', '苦', 'ヂ', '芲', '宁', '夢', '誉', '̨', '嗜', '掃', '仲', '噦', 'ゅ', '宮', '厄', '妙', '浪', '帯', '呂', '氾', 'ゟ', 'ř', '球', '雪', '蔛', '┆', '林', '®', '綴', '寄', '寿', '唱', '贜', '㈱', '机', '＞', '┙', '律', '嘎', '挨', '捷', '娘', '詞', '繋', '徳', '̶', '覼', '盟', '雛', '醸', '脚', '鷹', 'Ｘ', '忍', '氺', '葒', '瑆', '駆', '粘', '佐', '┖', '聡', '郡', '磨', '齢', '腕', '釘', '惧', '摯', '慨', '觛', '櫤', '祲', '渋', '釬', '齬', '蛍', '另', '⻌', '潒', '豳', '灯', '鉛', '封', '榀', 'ぺ', '遷', '𠛬', '稀', '拾', '＆', '嫮', '潰', '麗', '煙', '瀨', '投', '美', '筆', '吸', 'õ', '寺', '還', '瓤', '鬎', '硇', '函', ' 靭', '紐', '預', '┭', '☆', '銞', '頁', '⌆', 'Ⅲ', '昌', '碭', '⑬', '皿', '忠', '父', '𦉰', '師', '吟', '𨗈', '滞', '㝡', '募', 'Ⅱ', '⅔', 'ㇴ', '晋', '札', 'ɪ', '臨', '極', '綺', '痎', '歪', '堀', '頂', '壴', '将', '魫', '┎', '𣳾', '豊', '労', '骹', '℃', 'ヷ', '韓', '鶼', '；', '祀', '墩', '鍮', '＋', '閾', ' 矩', '涬', '駁', 'ű', '占', '毀', '旼', '墋', '懲', '崎', '麃', '𨂊', '√', '綿', '乖', '渉', '薝', '哲', '覗', '僙', '蜢', '婕', '靁', 'ś', '幌', '弾', '‹', '＃', '─', '累', '◎', '湘', '〜', 'ﬄ', '賡', 'ヨ', '花', '唵', '士', '裸', '敵', '唫', '礻', '⁰', '晟', '犬', '媞', '諐', '筭', 'ヮ', '妯', '擕', '硨', '席', '埋', '蒸', '句', '盾', '血', '斿', '┮', '暿', 'Ñ', '至', '堧', '鯳', 'É', '友', '𤇾', '週', '暭', '¡', '⑫', '瓊', '庶', 'ǐ', '霧', '鉏', '快', '̌', '嶲', '僅', '艦', '抗', 'ㇼ', '袚', '幹', '丸', '浜', '久', '鯥', '揺', '賵', '鈳', 'Ì', '◇', '譅', '援', '町', '鬫', '釡', '¢', '尋', 'ª', '怒', '醲', '讇', '騑', '遇', '犯', '愛', '°', '医', '敲', '浮', '籮', '鋌', '煅', 'Ｔ', '瞬', '泉', '猫', 'ǖ', '卑', '亡', '皽', '争', '┬', '獅', '棚', '土', '捗', 'Ẽ', '洲', '店', '勝', 'ｇ', '奵', 'ㇾ', '梨', '晴', '礴', '諔', '㗞', '炤', '滑', '－', '貫', '暫', '錯', '鍹', '周', 'ぷ', '掲', '｢', '┵', '輝', '縛', '滓', '»', '珍', '届', '薬', '宛', '懸', '鄘', '┍', '克', '斉', '縵', '弧', '清', '┯', '埧', '卡', '陣', 'Ĝ', '醎', '倒', '±', '稑', '喈', '貴', 'ă', '呦', '興', '官', '魅', 'ヺ', '娯', 'ヵ', '慈', '寝', '飽', ' 銀', '碻', '呴', '福', '̈', '氏', '智', '倉', 'ʀ', '呈', '﨑', '焦', '矢', '炅', '杯', '抱', '烈', '飛', '慌', '䒳', '沕', '晴', '訏', '〈', '̆', '裏', '訝', '酬', '捉', '傍', '麞', '瑕', '熠', 'ﬁ', 'ヶ', '媢', '∅', '暲', '‰', '臣', '敬', '訳', '淏', '剥', 'Ś', '↑', '棭', '迠', '楲', '濊', '岨', '灰', '売', ' 審', '＜', 'Ｓ', '溓', '恐', '欣', '吐', 'Ｑ', 'β', '輈', '襛', '娠', 'ˡ', 'ㇲ', '購', '也', '宿', 'Ⅳ', '翅', '繍', '岡', '牽', '巧', '兼', '┥', '阜', '富', '涖', '苏', '爆', 'Å', '匿', '砕', '鬉', 'ä', '噏', '陽', '飃', '□', '踧', '┧', '苢', '£', '些', '壁', '賁', '尽', '✓', 'é', '病', '辤', '鮮', '褦', '訪', '宙', '∑', '鯱', '碑', '敢', '誠', '燴', '瞀', '擤', '奇', '涯', '苔', '奥', '墀', '伸', '窪', '顕', 'æ', 'Ö', '疾', '看', '㟢', '贛', '┛', '苎', '髥', '芷', '\uf09f', '誌', '嘆', '松', '買', '典', '肝', '君', '玢', '阪', '阻', '笧', '鼫', 'ǹ', 'Δ', 'ヾ', '《', 'ゑ', '疵', '植', '衡', '┑', '鈴', '蛛', '羽', '薄', '剛', '叱', 'ƒ', '┢', '雯', '┞', '祖', '枝', '僧', 'Ő', '床', '盫', '拌', '鬙', '耗', '魔', '↓', '劣', '酥', '遝', '奪', '牂', '芽', '韖', '旅', '＝', '簿', '激', '剰', 'Ｄ', '├', '筋', '⊘', '甚', 'ぬ', '塗', '泒', '柳', '睎', '┕', '座', '郵', '♦', '愉', '‐', '昧', '丁', '偽', '擦', '殺', '殆', '楷', '園', '垂', '扇', '敏', '筁', '厨', '乏', '｝', '舎', '躍', '₄', '┟', '¸', '拶', '傘', '巨', '渇', ' 貸', '蹰', '俊', '抹', '┄', '敷', 'Ⅰ', '誕', '丈', '黤', '倫', '𝑇', '兵', '襲', '丮', '«', '┋', '橋', '塊', '酷', '躻', '巡', '鯈', '妹', '錬', '姿', '刈', '淸', '汲', '税', '県', '噱', '捧', '叩', '〝', '\uf860', '汯', '朝', '督', '„', '余', '䈇', '晒', '坂', '髖', '弊', '診', '草', '准', '嫌', '潨', '鈸', '諾', '梄', '輫', 'ｘ', '暇', '誘', '海', '頑', 'Ã', '鳳', '暠', '底', '老', '糊', '且', '襜', '鍊', '™', '揃', '妟', '鳴', '榊', '◉', '軹', '┲', '眺', '鱟', '唆', '級', '\uf0a8', '虐', '淲', '之', '沢', ' 悲', '閣', '́', '‡', '邪', '泡', 'ㇳ', '澌', '゚', '┈', '睍', '褏', '\uf861', 'ﬀ', '板', '鑑', '鮦', '雨', '宜', '窬', '粒', '蔑', '秈', '𝑁', '筠', '濁', '汜', '┤', '根', '％', '礛', '願', '潔', '曖', '唯', ' 幸', '歌', '屋', '隻', '沖', '片', '寛', '仰', '苕', '偶', '如', '桑', '筒', '薦', '癊', '衰', '啓', ' 眼', '閽', '迷', '┇', '膨', '塞', '┉', '乙', '邦', '㎡', '孝', '矛', '僰', '葉', '‒', '拓', '熟', '碔', '謝', '襇', '聖', '臓', '覻', '億', '伖', '宍', '免', '厚', '擋', '∃', '鱡', '÷', 'ｍ', '㚖', '峰', ' 鳲', '澇', '洞', '痛', '痢', '腰', '航', '洋', '双', '循', '狭', '宗', '獲', '践', 'Ĉ', '溱', '症', '旁', '隅', '罪', '銜', '寒', 'Ｕ', '淼', '゠', '誊', '鼻', 'ㇵ', '祝', '澯', '泊', '凍', '濹', '隙', '―', '彰', '檉', '蕿', '爴', '‘', '┊', '⊆', '柱', '濫', '覇', '櫬', '̚', '随', '耕', '熀', '儀', '⌘', '崇', '磈', '掘', '岩', '𥧔', '罡', '渶', '㴞', '圭', '摩', '响', '房', '慎', 'ぴ', '辦', '疫', '渞', '鷲', 'ㇷ', '弁', '勺', '雁', '催', '宅', '逎', '曜', '食', '剤', '需', '┒', '眠', '＼', '腐', '譲', '曲', '稉', '妻', '棰', '厩', '邸', '𝑃', '䢵', '遮', '益', '〔', '喜', '鸇', '風', '◼', '⑪', 'ﬂ', '杖', '㒈', ' 潤', '尺', '焼', '螎', '碰', '’', 'ㇸ', '讵', '迧', '暖', '⓺', '髪', '塚', 'º', '叵', '序', '島', '┡', '遂', '庭', '∞', '浸', '蒙', '鼉', '貰', '墜', '癖', '𣘺', '但', 'ヽ', 'ｙ', '据', '铦', '₉', '頃', '銹', '趕', '│', '談', '⇒', '泣', '扉', '神', '凹', '翻', '枯', '陳', '〒', '午', '̊', '縁', '族', '𨥉', ' 裁', '矰', '酳', '‚', '群', '舗', '瞭', '洩', '旹', '煆', '┌', '穴', '併', '療', '┶', '武', '幽', '是', '〃', '粗', '乗', '湄', '鮬', '徹', '癌', 'ς', '䠖', '懇', '玉', '肌', '盲', '核', '澥', '猥', '驚', '飴', '暮', '䐌'} (not included in accuracy test during training)
[67.1521] alphabet mismatch: chars in validation set only: {'猪', '鬼', '彦', '孫', '津', '恵', '肉', '征', 'Ｊ', '･', '拍', '裂', '脈', '煩', 'Ｇ', '岸', '春', '疎', 'ë', '遡', '荻', '亘', '朱', '梅', '辛', '亮', '街', '祈', '尊', '勇', '簱', 'ł', 'Ｌ', '畳', '河', 'Ｈ', '輔', '憲', '雅'} (not trained)
Initializing model ✓

```

**Comment by mittagessen** [comment]
Looks like it's bisecting time. 4854d3c8b3ae5344ad7c05f685787b203e7431ed is the last commit before merging the batches branch, if you could try that one I'd be much obliged.

**Comment by eighttails** [comment]
git bisect says:
2f604bc5be0cb39ad6c1329544f36e5f2aabfb17 is the first bad commit

But I have to tell you many revisions between 4854d3c and 7a94744d did not work due to another erros like `AttributeError: 'tuple' object has no attribute 'size'` and I had to do `git bisect skip` some times.
So 2f604bc5 might not be real regression.

**Comment by sixtyfive** [comment]
Hi all! I'm trying to run a training with the latest master, also to see how it influences memory consumption, but it's giving this:

```bash
jrs@rtx2060-cuda:~/rom$ ~/.local/bin/ketos train -d cuda:0 --threads 8 -o rom_26Mar_jrs2 -q dumb -N 1 _rom_total2/*.png
Building training set  [####################################]  6415/6415          
[4.4969] alphabet mismatch: chars in training set only: {'ً'} (not included in accuracy test during training) 
Initializing model ✓
stage 1/1  [#-----------------------------------]  44/802  00:06:57
Traceback (most recent call last):
  File "/home/jrs/.local/bin/ketos", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jrs/.local/lib/python3.8/site-packages/kraken/ketos.py", line 427, in train
    trainer.run(_print_eval, _draw_progressbar)
  File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/train.py", line 372, in run
    o = self.model.nn(input, seq_lens)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/layers.py", line 26, in forward
    inputs = module(*inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/layers.py", line 379, in forward
    o = o.view(siz[0], siz[1], siz[2], self.output_size)
RuntimeError: shape '[1, 8, 121, 512]' is invalid for input of size 491520
```

My own fault or possibly related?

**Comment by mittagessen** [comment]
* J. R. Schmid :: 2020-05-19 19:21 Tue:
> ```bash
> jrs@rtx2060-cuda:~/rom$ ~/.local/bin/ketos train -d cuda:0 --threads 8 -o rom_26Mar_jrs2 -q dumb -N 1 _rom_total2/*.png
> Building training set  [####################################]  6415/6415          
> [4.4969] alphabet mismatch: chars in training set only: {'ً'} (not included in accuracy test during training) 
> Initializing model ✓
> stage 1/1  [#-----------------------------------]  44/802  00:06:57
> Traceback (most recent call last):
>   File "/home/jrs/.local/bin/ketos", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/jrs/.local/lib/python3.8/site-packages/kraken/ketos.py", line 427, in train
>     trainer.run(_print_eval, _draw_progressbar)
>   File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/train.py", line 372, in run
>     o = self.model.nn(input, seq_lens)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/layers.py", line 26, in forward
>     inputs = module(*inputs)
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 550, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/jrs/.local/lib/python3.8/site-packages/kraken/lib/layers.py", line 379, in forward
>     o = o.view(siz[0], siz[1], siz[2], self.output_size)
> RuntimeError: shape '[1, 8, 121, 512]' is invalid for input of size 491520
> ```
> 
> My own fault or possibly related?

Not related but another bug in the batching code. Is your training set
public and is the error systematic, i.e. does it occur every time you're
running it? It looks like there's one output dimension (8 * 512 = 4096 =
1 * 8 * 121 * 512 - 491520) of the tensor missing.

Does it go away when using the `-B 1` option?

**Comment by sixtyfive** [comment]
> is the error systematic, i.e. does it occur every time you're running it? It looks like there's one output dimension (8 * 512 = 4096 = 1 * 8 * 121 * 512 - 491520) of the tensor missing.

Adding `-B 1` only changes the size to 61440 in the RuntimeError. Interestingly, that number is stable. Without the option, the sizes seem to be a dice roll between either 491520 or 499712 (a distance of 8192).  Adding `- B 2` only results in `… is invalid for input of size 122880`, though.

> Is your training set public

I'm uncertain as to whether it'd be okay to share it publically, but do know it'd be fine to share it with _you_ - my email address is schmidj at s a w dash leipzig dot de. If you could drop me a mail there I'll happily send a link back!

**Comment by mittagessen** [comment]
* J. R. Schmid :: 2020-05-19 22:38 Tue:
> Adding `-B 1` only changes the size to 61440 in the RuntimeError.
> Interestingly, that number is stable. Without the option, the sizes
> seem to be a dice roll between either 491520 or 499712 (a distance of
> 8192).  Adding `- B 2` only results in `… is invalid for input of size
> 122880`, though.

I did some more tests and the error seems to be related to cuda.

**Comment by sixtyfive** [comment]
> I did some more tests and the error seems to be related to cuda.

Yes, working fine with `-d cpu`. Is cuda unsupported in current master?

**Comment by mittagessen** [comment]
It should be supported. The fault lies in a divergence between the computed sequence length and the actual output of the layer (missing one time step). The formulas are probably screwed up somewhere, it's just that the cuda kernels crop the tensor to the maximum sequence length while the cpu kernels don't.

**Comment by mittagessen** [comment]
The crash bug is fixed now, the memory consumption one remains.

**Comment by sixtyfive** [comment]
Pulled and confirmed. Thank you, @mittagessen! FWIW, with my 7128 images of Arabic text (running without any command line options rn except for `--device cuda:0 --threads 8`) it's currently (mid-stage 3) at only 3.7GB system and 1.1GB GPU memory.

**Comment by sixtyfive** [comment]
Btw, I have no problem maxing the GPU out with other CUDA applications, but Ketos never manages to bring it beyond ~35% utilisation (according to `nividia-smi`, instead driving as many CPU cores as I throw at it to almost permanent 100%. Is that by design somehow or am I simply hitting an unavoidable bottleneck with the dated Xeon E3?

**Comment by mittagessen** [comment]
* J. R. Schmid :: 2020-05-20 13:56 Wed:
> Btw, I have no problem maxing the GPU out with other CUDA
> applications, but Ketos never manages to bring it beyond ~35%
> utilisation (according to `nividia-smi`, instead driving as many CPU
> cores as I throw at it to almost permanent 100%. Is that by design
> somehow or am I simply hitting an unavoidable bottleneck with the
> dated Xeon E3?

Throw more worker threads at it and crank up the batch size. The
defaults are set to make training on CPU bearable. Combined with the
fairly small model size this causes underutilization on any but the
smalled GPUs. On a RTX 2080 I'm getting 100% utilization with a batch
size of 64 with sufficient loaders. You'll have to adjust the
hyperparameters, chiefly by increasing the learning rate.

Fundamentally, the preprocessing is rather computationally expensive
though. You can circumvent that with the `--preload` option during
actual training but that one is extremely slow before training as it
isn't parallelized.

**Comment by sixtyfive** [comment]
Thank you, these helped a lot! I'll keep playing with that for a while. What are you using for `--lrate` on the 2080 (got a 2060 here)? Memory usage still seems fine with the Arabic model I sent you the training data for (still <4GB system memory and, with `-B 64`, ~4GB GPU memory). Could @eighttails's training data be what's contributing to triggering the bug?

**Comment by mittagessen** [comment]
> Thank you, these helped a lot! I'll keep playing with that for a
> while. What are you using for `--lrate` on the 2080 (got a 2060 here)?

That was just a quick run to see which batch size would get the best
utilization. I didn't dial in the hyperparameters. We're using mostly
the new segmenter with the baseline data nowadays and for both
computational and memory reasons these large batch sizes dont make sense
in our current setup. I'd start with something like 0.01 and lower it
progressively if the network doesn't converge.

> Memory usage still seems fine with the Arabic model I sent you the
> training data for (still <4GB system memory and, with `-B 64`, ~4GB
> GPU memory). Could @eighttails's training data be contributing to
> triggering the bug?

Yes, it's probably the baseline-style training data he's using (at least
I assume so as the box-style isn't supported when using XML ground
truth). With the default batch size of 8, 8 different page images have
to be loaded completely and a single line extracted for each. This is a
obviously fairly slow with a single loader thread but it shouldn't
gobble up 30Gb of memory if the source images aren't that large and it
worked before the merge.

**Comment by eighttails** [comment]
I found ketos gobbles memory even when there are only 2 images in the dataset.
Extract attached file, enter PAGE2 directory and do
`ketos train -f page --no-preload -F 1 -B 1 -o jpn *.xml`
ketos eats whole memory and training never starts.

[PAGE2.tar.gz](https://github.com/mittagessen/kraken/files/4673513/PAGE2.tar.gz)

**Comment by sixtyfive** [comment]
Confirmed. FWIW, even throwing 40GB at it is not enough.

**Comment by mittagessen** [comment]
* Tadahito Yao :: 2020-05-24 14:47 Sun:
> I found ketos gobbles memory even when there are only 2 images in the dataset.
> Extract attached file, enter PAGE2 directory and do
> `ketos train -f page --no-preload -F 1 -B 1 -o jpn *.xml`
> ketos eats whole memory and training never starts.

Thanks for the report with data. I'll take a look after a night of
sleep. Apparently, something broke during the merge.

**Comment by eighttails** [comment]
With latest master, the issue seems to be fixed.
Memory usage went back to about 2GB.
thanks.

**Comment by mittagessen** [comment]
* Tadahito Yao :: 2020-06-01 15:39 Mon:
> With latest master, the issue seems to be fixed.
> Memory usage went back to about 2GB.
> thanks.

Hm, interesting. I didn't change anything in that regard but there's a
separate feature branch with explicit tensor deletion.
